#!/usr/bin/env python3
"""Generate FSRS reference traces from py-fsrs (pip install fsrs==6.3.2) as a Kotlin
test-data file. Fuzzing is disabled so traces are deterministic.
Usage: python tools/fsrs_reference.py
"""
import random
from datetime import datetime, timedelta, timezone
from pathlib import Path
from fsrs import Scheduler, Card, Rating

OUT = Path(__file__).resolve().parent.parent / "core/src/commonTest/kotlin/app/quenya/core/FsrsReferenceData.kt"
START = datetime(2026, 1, 1, tzinfo=timezone.utc)
EPOCH = datetime(1970, 1, 1, tzinfo=timezone.utc)
ms = lambda dt: round((dt - EPOCH).total_seconds() * 1000)

def gap(rng, card):
    """Mix of same-session reviews, on-time reviews, and late reviews."""
    r = rng.random()
    if r < 0.25: return timedelta(minutes=rng.choice([1, 2, 5, 9, 30, 200]))
    due_in = max(card.due - cur[0], timedelta(0))
    if r < 0.7: return due_in + timedelta(minutes=rng.randint(0, 600))
    return due_in + timedelta(days=rng.randint(1, 60), hours=rng.randint(0, 23))

traces = []
sch = Scheduler(enable_fuzzing=False)
rng = random.Random(20261002)
for t in range(40):
    card, now, lines = Card(), START, []
    cur = [now]
    for i in range(30):
        g = timedelta(0) if i == 0 else gap(rng, card)
        now = now + g; cur[0] = now
        rating = rng.choices([Rating.Again, Rating.Hard, Rating.Good, Rating.Easy], [1, 2, 6, 2])[0]
        card, _ = sch.review_card(card, rating, now)
        lines.append(" ".join(map(str, [ms(now), int(rating), int(card.state),
                     -1 if card.step is None else card.step,
                     repr(card.stability), repr(card.difficulty), ms(card.due)])))
    traces.append("\\n".join(lines))

kt = ["package app.quenya.core", "",
      "// GENERATED by tools/fsrs_reference.py from py-fsrs 6.3.2 (fuzzing off). Do not edit.",
      "// Line format: nowMs rating state step stability difficulty dueMs   (step -1 = null)",
      "object FsrsReferenceData {", "    val traces: List<String> = listOf("]
kt += [f'        "{tr}",' for tr in traces]
kt += ["    )", "}", ""]
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("\n".join(kt), encoding="utf-8")
print("wrote", OUT, len(traces), "traces")
