#!/usr/bin/env python3
"""Turn the generated JSON assets into a Kotlin test fixture (core/src/commonTest/.../Fixtures.kt)
so the core logic can be tested against REAL data without a JSON library or Gradle.
Subset: all curriculum/phrases/lessons(summary only); forms for features used by the milestones;
lexicon entries referenced by phrases/forms plus the best-attested others (for distractors).
Usage: python tools/make_kotlin_fixtures.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
F = ROOT / "composeApp/src/commonMain/composeResources/files"
OUT = ROOT / "core/src/commonTest/kotlin/app/quenya/core/Fixtures.kt"
CHUNK, EXTRA_LEX = 120, 1500

def q(s):
    if s is None: return "null"
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$").replace("\n", "\\n") + '"'
def ql(xs): return "listOf(" + ", ".join(q(x) for x in xs) + ")" if xs else "emptyList()"
def b(x): return "true" if x else "false"

lex = json.load(open(F / "lexicon.json", encoding="utf-8"))
forms = json.load(open(F / "forms.json", encoding="utf-8"))
phrases = json.load(open(F / "phrases.json", encoding="utf-8"))
lessons = json.load(open(F / "lessons.json", encoding="utf-8"))
cur = json.load(open(F / "curriculum.json", encoding="utf-8"))

used = {f for p in phrases for t in p["tokens"] for f in t["features"]}
forms = [f for f in forms if set(f["features"]) & used and f["clean"]]
need = {t["lemma"] for p in phrases for t in p["tokens"] if t["lemma"]} | {f["lemma"] for f in forms}
need |= {l for s in cur for sl in s.get("slots", []) for l in sl.get("lemmas", [])}
byid = {e["id"]: e for e in lex}
chosen = [byid[i] for i in sorted(need) if i in byid]
rest = sorted((e for e in lex if e["id"] not in need and e["attestations"] >= 1 and e["gloss"]["en"]),
              key=lambda e: -e["attestations"])[:EXTRA_LEX]
lex = chosen + rest

def lex_kt(e): return f'LexiconEntry({q(e["id"])}, {q(e["lemma"])}, {q(e["pos"])}, Gloss({q(e["gloss"]["en"])}), {e["attestations"]}, {q(e["mark"])}, {b(e["deprecated"])}, {q(e["confidence"])})'
def form_kt(f): return f'FormEntry({q(f["lemma"])}, {q(f["surface"])}, {ql(f["features"])}, {q(f["source"])}, {b(f["clean"])})'
def tok_kt(t): return f'Token({q(t["text"])}, {q(t["punct"])}, {q(t["lemma"])}, {ql(t["features"])}, {q(t["gloss"])}, {q(t["resolution"])}, {q(t.get("guess"))})'
def ph_kt(p):
    toks = ", ".join(tok_kt(t) for t in p["tokens"])
    vs = ", ".join(f'Variant({q(v["text"])}, {q(v["source"])})' for v in p["variants"])
    return f'Phrase({q(p["id"])}, {p["order"]}, {q(p["text"])}, {q(p["gloss"])}, listOf({toks}), listOf({vs}), {q(p["textId"])}, {p["line"]}, {q(p.get("note"))})'
def les_kt(l): return f'Lesson({q(l["id"])}, {q(l["title"])}, {q(l["entry"])}, {b(l["generated"])}, {q(l["summary"])}, emptyList(), {q(l["source"])})'
def slot_kt(sl): return f'Slot({q(sl["kind"])}, {q(sl.get("title"))}, {q(sl.get("lesson"))}, {q(sl.get("feature"))}, {ql(sl.get("lemmas", []))}, {ql(sl.get("phrases", []))})'
def ses_kt(s): return f'Session({s["n"]}, listOf({", ".join(slot_kt(sl) for sl in s["slots"])}), {q(s.get("milestone"))}, {b(s.get("stretch", False))})'

lines = ["package app.quenya.core", "",
         "// GENERATED by tools/make_kotlin_fixtures.py from the real Eldamo-derived assets. Do not edit.",
         "object Fixtures {"]
def emit(name, typ, items, fn):
    chunks = [items[i:i + CHUNK] for i in range(0, len(items), CHUNK)] or [[]]
    for i, ch in enumerate(chunks):
        lines.append(f"    private fun {name}{i}(): List<{typ}> = listOf(")
        lines.extend(f"        {fn(x)}," for x in ch)
        lines.append("    )")
    lines.append(f"    private fun {name}(): List<{typ}> = " + " + ".join(f"{name}{i}()" for i in range(len(chunks))))
emit("lexicon", "LexiconEntry", lex, lex_kt)
emit("forms", "FormEntry", forms, form_kt)
emit("phrases", "Phrase", phrases, ph_kt)
emit("lessons", "Lesson", lessons, les_kt)
emit("curriculum", "Session", cur, ses_kt)
lines += ["    fun course() = CourseData(lexicon(), forms(), phrases(), lessons(), curriculum())", "}", ""]
OUT.write_text("\n".join(lines), encoding="utf-8")
print(f"wrote {OUT.name}: {len(lex)} lexicon, {len(forms)} forms, {len(phrases)} phrases, {len(lessons)} lessons, {len(cur)} sessions")
